export const PERMISSIONS = {
  // User Management
  CREATE_ADMIN: 'CREATE_ADMIN',
  EDIT_ADMIN: 'EDIT_ADMIN',
  DELETE_ADMIN: 'DELETE_ADMIN',
  
  CREATE_BROKER: 'CREATE_BROKER',
  EDIT_BROKER: 'EDIT_BROKER',
  DELETE_BROKER: 'DELETE_BROKER',
  
  CREATE_USER: 'CREATE_USER',
  EDIT_USER: 'EDIT_USER',
  DELETE_USER: 'DELETE_USER',
  DISABLE_USER: 'DISABLE_USER',
  
  VIEW_USERS: 'VIEW_USERS',
  VIEW_ALL_ACCOUNTS: 'VIEW_ALL_ACCOUNTS',
  
  // Platform & Configuration
  MANAGE_TEMPLATES: 'MANAGE_TEMPLATES',
  MANAGE_GLOBAL_SETTINGS: 'MANAGE_GLOBAL_SETTINGS',
  MANAGE_BROKERAGE_SETTINGS: 'MANAGE_BROKERAGE_SETTINGS',
  MANAGE_MARGIN_SETTINGS: 'MANAGE_MARGIN_SETTINGS',
  ASSIGN_ROLES: 'ASSIGN_ROLES',
  RESET_PASSWORDS: 'RESET_PASSWORDS',
  IMPERSONATE_USERS: 'IMPERSONATE_USERS',
  MANAGE_PERMISSIONS: 'MANAGE_PERMISSIONS',
  
  // Trading & Financials
  VIEW_TRADING_ACTIVITY: 'VIEW_TRADING_ACTIVITY',
  VIEW_REPORTS: 'VIEW_REPORTS',
  DEPOSIT_FUNDS: 'DEPOSIT_FUNDS',
  WITHDRAW_FUNDS: 'WITHDRAW_FUNDS',
  VIEW_USER_LEDGER: 'VIEW_USER_LEDGER',
  VIEW_USER_POSITIONS: 'VIEW_USER_POSITIONS',
  VIEW_USER_ORDERS: 'VIEW_USER_ORDERS',
  APPLY_TEMPLATES: 'APPLY_TEMPLATES',
  
  // Personal
  VIEW_OWN_PROFILE: 'VIEW_OWN_PROFILE',
  VIEW_OWN_WALLET: 'VIEW_OWN_WALLET',
  VIEW_OWN_LEDGER: 'VIEW_OWN_LEDGER',
  VIEW_OWN_POSITIONS: 'VIEW_OWN_POSITIONS',
  VIEW_OWN_ORDERS: 'VIEW_OWN_ORDERS',
  VIEW_OWN_TRADES: 'VIEW_OWN_TRADES',
  VIEW_OWN_REPORTS: 'VIEW_OWN_REPORTS',
} as const;

export type Permission = keyof typeof PERMISSIONS;
export type AppRole = 'super_admin' | 'admin' | 'broker' | 'user';

export const ROLE_PERMISSIONS: Record<AppRole, Permission[]> = {
  super_admin: [
    'CREATE_ADMIN', 'EDIT_ADMIN', 'DELETE_ADMIN',
    'CREATE_BROKER', 'EDIT_BROKER', 'DELETE_BROKER',
    'CREATE_USER', 'EDIT_USER', 'DELETE_USER', 'DISABLE_USER',
    'VIEW_USERS', 'VIEW_ALL_ACCOUNTS',
    'MANAGE_TEMPLATES', 'MANAGE_GLOBAL_SETTINGS', 'MANAGE_BROKERAGE_SETTINGS', 'MANAGE_MARGIN_SETTINGS',
    'ASSIGN_ROLES', 'RESET_PASSWORDS', 'IMPERSONATE_USERS', 'MANAGE_PERMISSIONS',
    'VIEW_TRADING_ACTIVITY', 'VIEW_REPORTS',
    'DEPOSIT_FUNDS', 'WITHDRAW_FUNDS',
    'VIEW_USER_LEDGER', 'VIEW_USER_POSITIONS', 'VIEW_USER_ORDERS', 'APPLY_TEMPLATES'
  ],
  admin: [
    'CREATE_BROKER', 'EDIT_BROKER', 'DELETE_BROKER',
    'CREATE_USER', 'EDIT_USER', 'DISABLE_USER',
    'VIEW_USERS',
    'MANAGE_TEMPLATES', 'APPLY_TEMPLATES', 'MANAGE_BROKERAGE_SETTINGS', 'MANAGE_MARGIN_SETTINGS',
    'VIEW_REPORTS'
  ],
  broker: [
    'CREATE_USER', 'EDIT_USER', 'DISABLE_USER',
    'VIEW_USERS',
    'DEPOSIT_FUNDS', 'WITHDRAW_FUNDS',
    'VIEW_USER_LEDGER', 'VIEW_USER_POSITIONS', 'VIEW_USER_ORDERS',
    'APPLY_TEMPLATES', 'MANAGE_BROKERAGE_SETTINGS'
  ],
  user: [
    'VIEW_OWN_PROFILE', 'VIEW_OWN_WALLET', 'VIEW_OWN_LEDGER',
    'VIEW_OWN_POSITIONS', 'VIEW_OWN_ORDERS', 'VIEW_OWN_TRADES', 'VIEW_OWN_REPORTS'
  ]
};

/**
 * Check if a given role has a specific permission.
 */
export function hasPermission(role: string, permission: Permission): boolean {
  if (!role) return false;
  const normalizedRole = (role === 'trader' ? 'user' : role) as AppRole;
  if (!(normalizedRole in ROLE_PERMISSIONS)) return false;
  return ROLE_PERMISSIONS[normalizedRole].includes(permission);
}
